CREATE TABLE IF NOT EXISTS encuestas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  materia VARCHAR(80) NOT NULL,
  titulo VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NULL,
  estado ENUM('PENDIENTE','HECHA') NOT NULL DEFAULT 'PENDIENTE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
